In [2]:
# # 주피터노트북 셀 스타일 조절
# from IPython.core.display import display, HTML
# # display(HTML("<style>.container { font-weight: bold !important; }</style>"))
# display(HTML("<style>.container { width: 100% !important; }</style>"))

# # 경고메시지 숨기기
# import warning
# warnings.filterwarnings(action='ignore')

# Numpy 개요
Numeric + Python = Numpy   
 - 수학 및 과학 연산을 위한 파이썬 패키지   
 - 배열이나 행렬 계산에 용이한 메서드를 제공   
 - 한글로 넘파이로 주로 통칭, 넘피/늄파이라고 부르기도 함   
 - 관련 사이트 : http://www.numpy.org   

일반 List에 비해 빠르고, 메모리 효율적   

 - 반복문 없이 데이터 배열에 대한 처리를 지원함   
 - 선형대수와 관련된 다양한 기능을 제공함   
 - Reference Site   
 - cs231 : http://cs231n.github.io/python-numpy-tutorial/#numpy   
 - https://docs.scipy.org/doc/numpy-dev/user/quickstart.html   
 - 데이터사이언스스쿨(파이썬버전) - https://goo.gl/3hsjbS   

설치 및 임포트   

 - 넘파이는 외부 라이브러리이므로 설치 필요.(아나콘다는 사전 설치됨)   
 - pip install numpy   

In [3]:
import numpy as np
np.__version__

'1.26.4'

## ndim(dimention, rank)
 - 몇 차원인지 반환

In [4]:
a = np.array(0)

In [5]:
a, a.ndim, type(a)

(array(0), 0, numpy.ndarray)

In [6]:
a = np.array([2, 4, 6])
a, a.ndim, type(a)

(array([2, 4, 6]), 1, numpy.ndarray)

In [7]:
a = [[1,2,3], [4,5,6]]
a

[[1, 2, 3], [4, 5, 6]]

In [5]:
a = np.array( [[1,2,3], [4,5,6]] )
a, a.ndim, type(a)

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 numpy.ndarray)

In [6]:
a.shape

(2, 3)

In [7]:
a = np.array( [ [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]] ] )
a, a.ndim, type(a)

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 3,
 numpy.ndarray)

In [8]:
a.shape

(2, 2, 3)

In [9]:
a = np.arange(10, 25).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 2,
 (3, 5),
 15)

In [12]:
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
# 행 뒤집기
a[::-1]

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14]])

In [11]:
# 열 뒤집기
a[::, ::-1]

array([[14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20]])

## 전치행렬

In [13]:
# 3행 2열
matrix_d = np.arange(1,7).reshape(3,2)
matrix_d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
# 2행 3열로 변환
print(matrix_d.T)

[[1 3 5]
 [2 4 6]]


In [15]:
# reshape과 transpose은 값이 다름을 유의 (reshqpe는 flatten이 선행)
print(matrix_d.reshape(2,3)) 

[[1 2 3]
 [4 5 6]]


## 난수로 구성된 넘파이 배열
 - np.random.randint(start, end, n) : 정수 난수
 - np.random.randint(start, end, (i, j))

In [16]:
np.random?

Type:        module
String form: <module 'numpy.random' from 'C:\\Users\\rhals\\anaconda3\\Lib\\site-packages\\numpy\\random\\__init__.py'>
File:        c:\users\rhals\anaconda3\lib\site-packages\numpy\random\__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
PCG64DXSM
Philox
SFC64
============================================= ===

============================================= ===
Getting entropy to initial

In [17]:
# 1~10 사이의 숫자중에서 10개 출력
np.random.randint(1, 10, 10)

array([1, 4, 7, 9, 8, 5, 2, 4, 6, 2])

In [18]:
np.random.randint(1, 49, 6)

array([22, 30, 29,  6, 43, 25])

In [19]:
# 2행 5열로 츨력
np.random.randint(1, 10, (2,5))

array([[1, 2, 4, 2, 9],
       [6, 9, 9, 7, 9]])

## 섞기
 - np.random.shuffle(넘파이배열) 원본에 바로 적용

In [20]:
np.random.shuffle?

Docstring:
shuffle(x)

Modify a sequence in-place by shuffling its contents.

This function only shuffles the array along the first axis of a
multi-dimensional array. The order of sub-arrays is changed but
their contents remains the same.

.. note::
    New code should use the `~numpy.random.Generator.shuffle`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
x : ndarray or MutableSequence
    The array, list or mutable sequence to be shuffled.

Returns
-------
None

See Also
--------
random.Generator.shuffle: which should be used for new code.

Examples
--------
>>> arr = np.arange(10)
>>> np.random.shuffle(arr)
>>> arr
[1 7 5 2 9 4 3 6 0 8] # random

Multi-dimensional arrays are only shuffled along the first axis:

>>> arr = np.arange(9).reshape((3, 3))
>>> np.random.shuffle(arr)
>>> arr
array([[3, 4, 5], # random
       [6, 7, 8],
       [0, 1, 2]])
Type:      builtin_function_or_method

In [21]:
# 10개 무작위 값 만들기
matrix_e = np.arange(1,11)
matrix_e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
np.random.shuffle(matrix_e)
matrix_e

array([ 9, 10,  5,  2,  4,  6,  7,  3,  1,  8])

### Quiz : 1~45까지 구성된 숫자 중에서 6개를 뽑아서 로또 번호를 생성하라

In [23]:
num= np.arange(1,46)
np.random.shuffle(num)
num[:6]

array([40, 29, 12,  1, 20, 13])

In [24]:
np.random.randint(1,46,6)

array([35, 23,  7, 40,  9,  5])

## 실수 난수
 - np.random.randn(n) np.random.randn(i, j)

In [25]:
np.random.randn?

Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    I

In [26]:
matrix1 = np.random.randn(10) # 표준정규분포 0 ~ 분산1
matrix1

array([ 1.74420508,  0.39359035,  0.01835077,  1.30771437,  1.04738365,
       -0.65163836,  0.43011297, -0.32465191,  1.1675824 ,  1.20368676])

In [27]:
matrix2 = np.random.randn(4, 4)
matrix2

array([[-1.36354906,  0.33395273, -0.19664713, -1.08604663],
       [-0.5911916 ,  0.85809136,  0.09143362,  0.80150119],
       [-2.00455644,  0.49001167, -0.3076613 ,  0.71337686],
       [ 2.24847278, -1.53972522,  0.94095745,  0.02850997]])

In [28]:
matrix1.max(), matrix1.min()

(1.7442050830070872, -0.6516383632618549)

In [29]:
np.random.choice?

Docstring:
choice(a, size=None, replace=True, p=None)

Generates a random sample from a given 1-D array

.. versionadded:: 1.7.0

.. note::
    New code should use the `~numpy.random.Generator.choice`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
a : 1-D array-like or int
    If an ndarray, a random sample is generated from its elements.
    If an int, the random sample is generated as if it were ``np.arange(a)``
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
replace : boolean, optional
    Whether the sample is with or without replacement. Default is True,
    meaning that a value of ``a`` can be selected multiple times.
p : 1-D array-like, optional
    The probabilities associated with each entry in a.
    If not given, the sample assumes a unif

## 집계함수에서의 축
 - 2차원에서의 집계합수(sum, mean)
 - axis = 0, 1
 - np.sum(넘파이배열, axis=0/1)
 - np.mean(넘파이배열, axis=0/1)
 - np.sort(넘파이배열, axis=0/1)

In [30]:
m1 = np.random.randint(1, 50, (5,5))
m1

array([[20, 47, 39, 34,  2],
       [12, 36, 47, 23, 43],
       [37,  2,  2, 25, 18],
       [28, 24, 32, 11, 45],
       [40, 28,  2, 23,  3]])

In [31]:
np.sum?

Signature:      
np.sum(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Call signature:  np.sum(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sum at 0x000001E0C3A6A8E0>
File:            c:\users\rhals\anaconda3\lib\site-packages\numpy\core\fromnumeric.py
Docstring:      
Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator in w

In [32]:
np.sum(m1, axis=0) # (x)열 합계

array([137, 137, 122, 116, 111])

In [33]:
np.sum(m1, axis=1) # (y)행 합계

array([142, 161,  84, 140,  96])

In [34]:
# 1번째행의 합계는
m1[0,:]

array([20, 47, 39, 34,  2])

In [37]:
# 1번째행의 합계는
np.sum(m1[0,:], axis=0) # x축(행 방향) 합계

142

### Quiz 3번째 열의 합계

In [39]:
np.sum(m1[:,2],axis=0)

122

## np.sort()

In [40]:
import numpy as np

In [41]:
# 정수 난수로 구성된 4x3
m2 = np.random.randint(1, 50,(4,3))
m2

array([[23, 35, 11],
       [ 9, 44, 35],
       [ 6,  9, 34],
       [ 8, 36, 21]])

In [42]:
np.sort?

Signature:       np.sort(a, axis=-1, kind=None, order=None)
Call signature:  np.sort(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sort at 0x000001E0C3A69760>
File:            c:\users\rhals\anaconda3\lib\site-packages\numpy\core\fromnumeric.py
Docstring:      
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list of

In [57]:
m2

array([[23, 35, 11],
       [ 9, 44, 35],
       [ 6,  9, 34],
       [ 8, 36, 21]])

In [55]:
np.sort(m2) # 행안에서 열정렬 default axis = -1

array([[11, 23, 35],
       [ 9, 35, 44],
       [ 6,  9, 34],
       [ 8, 21, 36]])

In [45]:
np.sort(m2, axis=0) # 행방향 오름차순(요소별로)

array([[ 6,  9, 11],
       [ 8, 35, 21],
       [ 9, 36, 34],
       [23, 44, 35]])

In [63]:
m2[::-1, ::] # 행전체가 역순으로 바뀌는 것과는 다르다(+sort는 요소별 정렬)

array([[ 8, 36, 21],
       [ 6,  9, 34],
       [ 9, 44, 35],
       [23, 35, 11]])

In [62]:
m2[::, ::-1]

array([[11, 35, 23],
       [35, 44,  9],
       [34,  9,  6],
       [21, 36,  8]])

In [58]:
m2[::-1]

array([[ 8, 36, 21],
       [ 6,  9, 34],
       [ 9, 44, 35],
       [23, 35, 11]])

In [61]:
m2[::]

array([[23, 35, 11],
       [ 9, 44, 35],
       [ 6,  9, 34],
       [ 8, 36, 21]])

In [47]:
m2

array([[23, 35, 11],
       [ 9, 44, 35],
       [ 6,  9, 34],
       [ 8, 36, 21]])

In [48]:
np.sort(m2, axis=1) # 행정렬 (열방향 오름차순)

array([[11, 23, 35],
       [ 9, 35, 44],
       [ 6,  9, 34],
       [ 8, 21, 36]])

In [60]:
m2[::-1, ::-1] 

array([[21, 36,  8],
       [34,  9,  6],
       [35, 44,  9],
       [11, 35, 23]])

## 인덱스 소팅
np.argsort(넘파이배열, axis=0,1)   

정렬값을 인덱스로 반환 (np.sort()를 인덱스로)   

In [51]:
x = np.array([9,5,4])
np.argsort(x) # 오름차순 정렬 4 5 9 의 인덱스 값 

array([2, 1, 0], dtype=int64)

In [52]:
x[np.argsort(x)] # 인덱스값으로 실제 값 출력

array([4, 5, 9])

## 넘파이 배열 요소 추가와 삭제
 - 삽입

np.insert(배열, 위치인덱스, 값, axis=0/1)
2차원인 경우 axis를 설정하지 않으면 1차원 배열로 변경되어 삽입출력
삭제

np.delete(배열명, 위치인덱스, axis=0/1)

In [65]:
m3 = np.arange(1,11)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
np.insert?

Signature:       np.insert(arr, obj, values, axis=None)
Call signature:  np.insert(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function insert at 0x000001E0C3CBBEC0>
File:            c:\users\rhals\anaconda3\lib\site-packages\numpy\lib\function_base.py
Docstring:      
Insert values along the given axis before the given indices.

Parameters
----------
arr : array_like
    Input array.
obj : int, slice or sequence of ints
    Object that defines the index or indices before which `values` is
    inserted.

    .. versionadded:: 1.8.0

    Support for multiple insertions when `obj` is a single scalar or a
    sequence with one element (similar to calling insert multiple
    times).
values : array_like
    Values to insert into `arr`. If the type of `values` is different
    from that of `arr`, `values` is converted to the type of `arr`.
    `values` should be shaped so that ``arr[...,obj,...] = values``
    is legal.
axis : int, optional
    Axis along whi

In [66]:
np.insert(m3, 0, 100)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [67]:
m3[0]

1

In [70]:
m3[-1]

10

In [71]:
np.insert(m3, -1, 500)  # 인덱싱/슬라이싱 end처럼 인식

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 500,  10])

In [72]:
np.insert(m3, len(m3), 500) 

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 500])

In [73]:
m4 = np.arange(1,10).reshape(3,3)
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
np.insert(m4, 0, 100) # 2차원배열의 경우 axis 미설정시 1차원으로 변경되어 삽입

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [75]:
# 1열으로 [100,100,100] 삽입
np.insert(m4, 0, 100, axis=1)

array([[100,   1,   2,   3],
       [100,   4,   5,   6],
       [100,   7,   8,   9]])

In [76]:
# 리스트로 삽입
np.insert(m4, 0, [100,200,300], axis=1)

array([[100,   1,   2,   3],
       [200,   4,   5,   6],
       [300,   7,   8,   9]])

In [77]:
m4.shape, m4.shape[1], len(m4)

((3, 3), 3, 3)

In [78]:
# 마지막 컬럼으로 삽입
# 배열명.shape[1] 칼럼 길이
np.insert(m4, m4.shape[1], [100,200,300], axis=1)

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200],
       [  7,   8,   9, 300]])

In [79]:
# 마지막 행에 삽입
np.insert(m4, m4.shape[0], [100,200,300], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100, 200, 300]])

In [80]:
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
np.delete(m4, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

## 배열 합치기
 - np.vstack((배열1,배열2....)) : 세로 합치기
 - np.hstack((배열1,배열2....)) : 가로 합치기
 - np.concatenate((배열1, 배열2), axis=0/1 ) 2차원만 가능

In [82]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
np.hstack((a,b)), np.hstack((a,b)).ndim , np.hstack((a,b)).shape

(array([1, 2, 3, 4, 5, 6]), 1, (6,))

In [85]:
c = np.array([[1,2,3]]) # 2차원
c, c.ndim, c.shape

(array([[1, 2, 3]]), 2, (1, 3))

In [86]:
d = np.array([[4,5,6]]) # 2차원
d, d.ndim, d.shape

(array([[4, 5, 6]]), 2, (1, 3))

In [87]:
f = np.concatenate((c,d), axis=0) #
f, f.ndim, f.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [90]:
f = np.concatenate((c,d), axis=1) #
f, f.ndim, f.shape

(array([[1, 2, 3, 4, 5, 6]]), 2, (1, 6))

## boolean indexing, mask
 - 조건절의 결과는 True, False로 반환
 - True인 결과의 데이터 반환
 - 넘파이배열[조건절] : ==, !=, <=, >=, &, |, ~

In [91]:
matrix = np.arange(1, 21)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [92]:
matrix > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [93]:
matrix[matrix > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [94]:
(matrix > 10).sum()

10

In [95]:
len(matrix[matrix > 10])

10

### Quiz : 1~100사이 난수 30개를 추출하여 넘파이 배열을 생성하고, 30보다 크거나 70보다 작은 수를 출력하라

In [97]:
np.random.randint(1, 100, 30)

array([16, 60, 29,  1, 42, 94, 41, 78, 40, 65, 41, 62,  6,  1, 34, 82, 13,
       81, 63, 71,  1, 15, 75, 92, 68, 33, 98, 98, 45, 54])

In [98]:
matrix = np.random.randint(1, 100, 30)
matrix

array([29, 49, 28, 74, 93, 57,  5, 27, 68, 52, 31, 55, 71, 83, 55, 72, 10,
       71, 84, 82, 14,  5, 68, 10, 66, 77, 96, 66, 30,  6])

In [108]:
(matrix>30) & (matrix<70)

array([False,  True, False, False, False,  True, False, False,  True,
        True,  True,  True, False, False,  True, False, False, False,
       False, False, False, False,  True, False,  True, False, False,
        True, False, False])

In [110]:
matrix[(matrix>30) & (matrix<70)]

array([49, 57, 68, 52, 31, 55, 55, 68, 66, 66])

### Quiz2 : 10보다 작거나 90보다 큰수 출력하기

In [112]:
matrix = np.random.randint(1, 100, 30)
matrix

array([43, 42, 25,  7, 83, 20, 88, 74, 28, 39, 44, 89, 54, 69,  4, 41, 98,
       93, 74, 61, 70, 19, 29, 75, 13, 49, 37, 43, 97, 41])

In [116]:
matrix[(matrix<10) | (matrix>90)]

array([ 7,  4, 98, 93, 97])

## fancy indexing(filtering)
넘파이 배열에 배열로 인덱싱하면 인덱스 번호로 인식한다.

 - 넘파이배열1[넘파이배열2]
 - 넘파이배열2 : 인덱스 역할 (only 정수형)

In [117]:
n = np.random.randint(1,100,30)
i = np.array([0, 2, 3, 10, 20])
n, n[i]

(array([94, 86, 34, 49, 17, 32, 38, 70, 58, 76,  4, 59,  9, 41, 90, 64, 75,
        94, 45, 76,  8, 26, 64, 20, 67, 90, 66, 93, 70,  3]),
 array([94, 34, 49,  4,  8]))

## np.where()를 이용한 필터링
 - np.where(조건식) : 조건식 만족하는 인덱스 반환
 - np.where(조건식, T, F) : 조건식 만족하면 T값, 아니면F값
 - 배열[np.where(조건식)] : 조건식 만족하는 실제 배열값

In [118]:
np.where?

Call signature:  np.where(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function where>
Docstring:      
where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes


In [119]:
a = np.arange(10)
a, np.where(a < 5, a, 10*a)
# a가 5보다 작으면 a를, 아니면 10을 곱하여 출력

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90]))

In [120]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [121]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])